# Generated by Django 5.1.7 on 2025-03-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_initial_metadata'),
        ('user', '0012_alter_metadata_funds'),
    ]

    operations = [
    ]
